### ISSUE TITLE
hi，How to generate text

### ISSUE THREAD

**Issue by Jeremiah0425** [KaijuML/rotowire-rg-metric#4]
I have completed the training, how to use the model to generate a summary.thanks

**Comment by KaijuML** [comment]
Hi, 

This repo is about training a metric, and will never yield a model able to generate text. If you're interested in generating basketball descriptions, I suggest either my other repo: https://github.com/KaijuML/data-to-text-hierarchical or the also very good repo of Ratish Puduppully: https://github.com/ratishsp/data2text-macro-plan-py

I am closing this issue, 
Clément
